services:
  trivia-db:
    image: postgres:14.9
    volumes:
      - trivia_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - trivia-network
  
  trivia-api:
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
    command: /start
    volumes:
      - .:/opt/trivia
    env_file:
      - ./.env
    ports:
      - "5125:5125"
    networks:
      - trivia-network
    depends_on:
      - trivia-db

  frontend:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    volumes:
      - .:/opt/trivia
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - trivia-network
    depends_on:
      - trivia-api
    
  nginx:
    build: ./compose/nginx
    ports:
      - "8090:80"
    depends_on:
      - prod-frontend
    volumes:
      - .:/opt/trivia
    networks:
      - trivia-network

networks:
  trivia-network:
    driver: bridge

volumes:
  trivia_postgres_data: