"""empty message

Revision ID: 7eed22db550f
Revises: 4408ef8fb5ac
Create Date: 2024-02-22 23:05:54.795369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eed22db550f'
down_revision = '4408ef8fb5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
